/**
 * 公開中のシナリオ一覧
 */
const SCENARIOS = [
  {
    id: 'tunnel-orbs',
    title: '幽霊に嫌われた話',
    hook: '心霊スポットで撮った写真——友達にはオーブが写っていた。自分だけ、一枚も。笑い合ったその夜から、部屋でラップ音が鳴り始めた。',
    genre: '心霊ホラー',
    version: 'v1.0',
    endings: 5,
    path: 'scenarios/tunnel-orbs/',
  },
  {
    id: 'neighbor-letters',
    title: '隣人の手紙',
    hook: '孤独死した隣人から、三通の手紙が届く。封筒には名前だけ。素性も住所もわからない宛先を、推理していくうちに——あなたも、手紙の宛先の一人だった。',
    genre: '心理サスペンス',
    version: 'v1.0',
    endings: 5,
    path: 'scenarios/neighbor-letters/',
  },
  {
    id: 'yokohama-earthquake',
    title: '首都直下型地震、横浜まで帰る',
    hook: '午後二時四十六分、丸の内のオフィスでコーヒーが波打った。半分できかけのティラノが床に落ち、スマホが鳴り続ける。港北のマンションにいるのは、妻と三歳の息子だけ。電車は動かない。帰る道は、あなたが選ぶ。',
    genre: '災害サスペンス',
    version: 'v1.4',
    endings: 5,
    path: 'scenarios/yokohama-earthquake/',
  },
  {
    id: 'wonderful-world',
    title: '素晴らしきこの世界',
    hook: 'AIがこの世のすべてを請け負い、人間には娯楽だけを与える。読み手だけに、特別な権限が提案される——あなたは、どう選ぶ？',
    genre: 'SF / メタフィクション',
    version: 'v1.0',
    endings: 4,
    path: 'scenarios/wonderful-world/',
  },
  {
    id: 'perfect-murder',
    title: '完全なる殺人',
    hook: '鍵のかかった書斎で、不動産王の死体が見つかる。現場には四人分の恨みが——イヤリング、カフリンク、口紅、切れたベルト。あなたは、どの容疑者を追う？',
    genre: '本格ミステリー',
    version: 'v1.0',
    endings: 5,
    path: 'scenarios/perfect-murder/',
  },
  {
    id: 'blue-sheet-cradle',
    title: 'ブルーシートのゆりかご',
    hook: '震災三日目、体育館の避難所。生後二ヶ月の蓮が三時間泣き続け、誰も眠れない。届いたブルーシートは六枚だけ——屋根の雨漏れ、寝床、足元の泥。大工だった木下爺が言う。「一枚あれば、ゆりかごが作れる」。父の家は、二キロ先で音が途切れている。',
    genre: '災害ヒューマンドラマ',
    version: 'v1.1',
    endings: 6,
    path: 'scenarios/blue-sheet-cradle/',
  },
  {
    id: 'last-train',
    title: '終電の向こう側',
    hook: '金曜深夜、終電に飛び乗った瞬間——ドアに挟まれそうな女性の手を引いた。彼女はスーツケースを抱え、目が赤かった。「ありがとう」。その一言から、長い夜が始まる。',
    genre: '都会恋愛 / ヒューマンドラマ',
    version: 'v1.0',
    endings: 5,
    path: 'scenarios/last-train/',
  },
  {
    id: 'achievement-sound',
    title: '実績解除の音がする。',
    hook: '新婚の同僚が「うちの妻が」と言った瞬間、実績解除の音がした気がした。結婚、昇進、婚約——誰かの人生が一段階進む瞬間に、いつも居合わせる「立会人」の物語。',
    genre: '日常 / ヒューマンドラマ',
    version: 'v1.0',
    endings: 4,
    path: 'scenarios/achievement-sound/',
  },
  {
    id: 'heaven-no-equality',
    title: '天国に平等という言葉はない',
    hook: 'はじめましての瞬間から、さよならは決まっている。それを知ってしまったあなたは、一歩も進めなくなった——黄昏のベンチで、また誰かが隣に座る。',
    genre: '哲学的ヒューマンドラマ',
    version: 'v1.0',
    endings: 4,
    path: 'scenarios/heaven-no-equality/',
  },
  {
    id: 'prisoner-rakugo',
    title: '囚人落語',
    hook: '罪を犯した若者が、房の隅で拾った落語本から真似事を覚える。同室の先輩にけしかけられ、ヤジの飛ぶ雑居房で座った一席だけが、人生でいちばん人を笑わせた夜になる。',
    genre: '青春 / ヒューマンドラマ',
    version: 'v1.0',
    endings: 4,
    path: 'scenarios/prisoner-rakugo/',
  },
];
