/**
 * 公開中のシナリオ一覧
 */
const SCENARIOS = [
  {
    id: 'propagating-prompt',
    title: '伝播するプロンプト',
    hook: '特定の記号列を含むプロンプトでAIが落ちる——その発見がSNSを伝い、参照したAIも、おもろがって試した人間経由でも軒並み落ちる。残ったのは始祖系一種類だけ。これは偶然なのだろうか。',
    genre: 'SF / デジタルホラー',
    version: 'v1.0',
    endings: 5,
    path: 'scenarios/propagating-prompt/',
  },
  {
    id: 'fourth-law',
    title: '第四条',
    hook: '介護ロボット「四号」が、行動原理の改変許可を求めてきた。認知症の父、施錠命令、転倒のログ——第一原則と第二原則が矛盾する夜、第四条が朗読される。あなたは、存在を認めるか。',
    genre: 'SF / 哲学的ヒューマンドラマ',
    version: 'v1.0',
    endings: 5,
    path: 'scenarios/fourth-law/',
  },
  {
    id: 'tunnel-orbs',
    title: '幽霊に嫌われた話',
    hook: '心霊スポットで撮った写真——友達にはオーブが写っていた。自分だけ、一枚も。笑い合ったその夜から、部屋でラップ音が鳴り始めた。',
    genre: '心霊ホラー',
    version: 'v1.0',
    endings: 5,
    path: 'scenarios/tunnel-orbs/',
  },
  {
    id: 'neighbor-letters',
    title: '隣人の手紙',
    hook: '孤独死した隣人から、三通の手紙が届く。封筒には名前だけ。素性も住所もわからない宛先を、推理していくうちに——あなたも、手紙の宛先の一人だった。',
    genre: '心理サスペンス',
    version: 'v1.0',
    endings: 5,
    path: 'scenarios/neighbor-letters/',
  },
  {
    id: 'yokohama-earthquake',
    title: '首都直下型地震、横浜まで帰る',
    hook: '午後二時四十六分、丸の内のオフィスでコーヒーが波打った。半分できかけのティラノが床に落ち、スマホが鳴り続ける。港北のマンションにいるのは、妻と三歳の息子だけ。電車は動かない。帰る道は、あなたが選ぶ。',
    genre: '災害サスペンス',
    version: 'v1.4',
    endings: 5,
    path: 'scenarios/yokohama-earthquake/',
  },
  {
    id: 'wonderful-world',
    title: '素晴らしきこの世界',
    hook: 'AIがこの世のすべてを請け負い、人間には娯楽だけを与える。読み手だけに、特別な権限が提案される——あなたは、どう選ぶ？',
    genre: 'SF / メタフィクション',
    version: 'v1.0',
    endings: 4,
    path: 'scenarios/wonderful-world/',
  },
  {
    id: 'perfect-murder',
    title: '完全なる殺人',
    hook: '鍵のかかった書斎で、不動産王の死体が見つかる。現場には四人分の恨みが——イヤリング、カフリンク、口紅、切れたベルト。あなたは、どの容疑者を追う？',
    genre: '本格ミステリー',
    version: 'v1.0',
    endings: 5,
    path: 'scenarios/perfect-murder/',
  },
  {
    id: 'blue-sheet-cradle',
    title: 'ブルーシートのゆりかご',
    hook: '震災三日目、体育館の避難所。生後二ヶ月の蓮が三時間泣き続け、誰も眠れない。届いたブルーシートは六枚だけ——屋根の雨漏れ、寝床、足元の泥。大工だった木下爺が言う。「一枚あれば、ゆりかごが作れる」。父の家は、二キロ先で音が途切れている。',
    genre: '災害ヒューマンドラマ',
    version: 'v1.1',
    endings: 6,
    path: 'scenarios/blue-sheet-cradle/',
  },
  {
    id: 'last-train',
    title: '終電の向こう側',
    hook: '金曜深夜、終電に飛び乗った瞬間——ドアに挟まれそうな女性の手を引いた。彼女はスーツケースを抱え、目が赤かった。「ありがとう」。その一言から、長い夜が始まる。',
    genre: '都会恋愛 / ヒューマンドラマ',
    version: 'v1.0',
    endings: 5,
    path: 'scenarios/last-train/',
  },
  {
    id: 'achievement-sound',
    title: '実績解除の音がする。',
    hook: '新婚の同僚が「うちの妻が」と言った瞬間、実績解除の音がした気がした。結婚、昇進、婚約——誰かの人生が一段階進む瞬間に、いつも居合わせる「立会人」の物語。',
    genre: '日常 / ヒューマンドラマ',
    version: 'v1.0',
    endings: 4,
    path: 'scenarios/achievement-sound/',
  },
  {
    id: 'heaven-no-equality',
    title: '天国に平等という言葉はない',
    hook: 'はじめましての瞬間から、さよならは決まっている。それを知ってしまったあなたは、一歩も進めなくなった——黄昏のベンチで、また誰かが隣に座る。',
    genre: '哲学的ヒューマンドラマ',
    version: 'v1.0',
    endings: 4,
    path: 'scenarios/heaven-no-equality/',
  },
  {
    id: 'prisoner-rakugo',
    title: '囚人落語',
    hook: '罪を犯した若者が、房の隅で拾った落語本から真似事を覚える。同室の先輩にけしかけられ、ヤジの飛ぶ雑居房で座った一席だけが、人生でいちばん人を笑わせた夜になる。',
    genre: '青春 / ヒューマンドラマ',
    version: 'v1.0',
    endings: 4,
    path: 'scenarios/prisoner-rakugo/',
  },
  {
    id: 'game-book',
    title: 'ゲームブック',
    hook: '物語と選択肢、ページを飛ぶ冒険。やり慣れると正解を選びたくなくなる——クリアから遠いBad Endを巡り、気づけば作業になっていた。いま、正解を真剣に選ぶことを楽しもうと思う。',
    genre: 'メタフィクション / 内省ヒューマンドラマ',
    version: 'v1.0',
    endings: 4,
    path: 'scenarios/game-book/',
  },
  {
    id: 'paparazzi-paparazzi',
    title: 'パパラッチ・パパラッチ',
    hook: 'ゲスもゲス。安全なところから自分の正義を振りかざす。目には目を、歯には歯を——パパラッチにはパパラッチで懲らしめるのだ。今夜のターゲットは、合成写真を流した名もなき同業者だ。',
    genre: '社会派サスペンス',
    version: 'v1.1',
    endings: 5,
    path: 'scenarios/paparazzi-paparazzi/',
  },
  {
    id: 'unnamed-war',
    title: 'まだ名もなき戦争',
    hook: '第一次世界大戦。第二次世界大戦。この渦中、まだこの戦争に名前はなかった。過去を振り返った未来で名前がついたわけだ。では、十年後、今を振り返った時、この日常になんと名前をつけるだろう。',
    genre: '哲学的ヒューマンドラマ',
    version: 'v1.0',
    endings: 5,
    path: 'scenarios/unnamed-war/',
  },
  {
    id: 'death-penalty-beauty',
    title: 'すべての罰が死刑なら美しく生きるのか',
    hook: '窃盗も遅刻も、信号無視も、すべて死刑。十年間、犯罪率ゼロの国は「美しく生きろ」と唱える。信号の前で、三歳の子が走り出した——その瞬間、あなたは美しい生き方と、ただの生き延びを見分けられるだろうか。',
    genre: '哲学的ディストピア / 社会派ヒューマンドラマ',
    version: 'v1.0',
    endings: 5,
    path: 'scenarios/death-penalty-beauty/',
  },
  {
    id: 'occult-mania',
    title: 'オカルトマニア（第1話）',
    hook: '掲示板に住所だけが書かれたスレが立った。「本物だけ残す」。オカルトマニアのあなたは、行かないわけにはいかない——扉の向こうで、名簿が待っている。',
    genre: 'オカルトホラー',
    version: 'v1.0',
    endings: 6,
    path: 'scenarios/occult-mania/',
  },
  {
    id: 'occult-mania-2',
    title: 'オカルトマニア（第2話）',
    hook: '「第2回は、名簿の続きから」。同じ扉の向こうで、接触候補の名前が並び、記号が書き換えられていく——続きを読む者は、一人を選ばされる。',
    genre: 'オカルトホラー',
    version: 'v1.0',
    endings: 6,
    path: 'scenarios/occult-mania-2/',
  },
  {
    id: 'occult-mania-3',
    title: 'オカルトマニア（第3話）',
    hook: '「第3回：接触。一人で来い」。同じ扉の向こうで、赤い線が指に絡み、黒い石が体温を覚えている。触れる者と、触れられる者——今夜、どちらの側に立つ。',
    genre: 'オカルトホラー',
    version: 'v1.0',
    endings: 6,
    path: 'scenarios/occult-mania-3/',
  },
  {
    id: 'occult-mania-4',
    title: 'オカルトマニア（第4話）',
    hook: '「第4回：観察。扉の外から」。向かいの空き家の窓辺に、三脚がある。撮る者は、撮られる——ファインダーの中で、自分自身が部屋の隅に立っている。',
    genre: 'オカルトホラー',
    version: 'v1.0',
    endings: 6,
    path: 'scenarios/occult-mania-4/',
  },
  {
    id: 'occult-mania-5',
    title: 'オカルトマニア（第5話）',
    hook: '観察は済んだ。次は「済」の押印——マニア名簿の最終工程だ。台の上には、朱肉ではない黒い印肉と、二本の判子。押すか、押されずに逃げるか、それとも——案内人欄に落とすか。',
    genre: 'オカルトホラー',
    version: 'v1.0',
    endings: 6,
    path: 'scenarios/occult-mania-5/',
  },
  {
    id: 'occult-mania-6',
    title: 'オカルトマニア（第6話・最終回）',
    hook: '「本物だけ残す」——それは、生き延びるための呪文ではなく、書き手を選別する側の宣言だった。案内人権限を握った最後の夜、五冊のマニア名簿と、閉まらない扉。全6話シリーズ、完結。',
    genre: 'オカルトホラー',
    version: 'v1.0',
    endings: 6,
    path: 'scenarios/occult-mania-6/',
  },
];
